Repository Arquisoft/wiq_en2b, pull requests merged in 2024-03, with the labels that each got.

#56 chore: webapp routing rewrite
  webapp/src/components/Router.jsx
Labels: frontend 👁️

#54 chore: fixing some tables, plantuml diagrams and writing a title for …
  docs/index.adoc
  docs/src/01_introduction_and_goals.adoc
  docs/src/03_system_scope_and_context.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/11_technical_risks.adoc
Labels: documentation 📜

#70 fix: cors configuration origins
  api/src/main/java/lab/en2b/quizapi/auth/config/SecurityConfig.java
Labels: bug 🐛, backend ⚙️, ASAP 🚨

#64 Feat/webapp/new login
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/ButtonEf.jsx
  webapp/src/components/Layout.jsx
  webapp/src/components/Layout.test.js
  webapp/src/components/Router.jsx
  webapp/src/components/pages.json
  webapp/src/pages/Login.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/styles/AppView.css
  webapp/src/tests/Login.test.js
Labels: frontend 👁️

#79 Feat/webapp/new dashboard
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/ButtonEf.jsx
  webapp/src/components/Router.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Rules.test.js
  webapp/src/tests/Signup.test.js
Labels: frontend 👁️

#84 feat: Adding the home page and tests for it
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/pages/Root.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/tests/Root.test.js
Labels: frontend 👁️

#90 feat: adding the login tests.
  webapp/src/tests/Login.test.js
Labels: frontend 👁️

#92 hotfix: removed unused Button import
  webapp/src/pages/Signup.jsx
Labels: frontend 👁️

#83 feat: add jwt authentication support
  sonar-project.properties
  webapp/.env
  webapp/.gitignore
  webapp/src/components/auth/AuthUtils.js
  webapp/src/i18n.js
  webapp/src/index.js
  webapp/src/pages/Login.jsx
  webapp/src/pages/Root.jsx
  webapp/src/tests/AuthUtils.test.js
Labels: enhancement 🆕, backend ⚙️, frontend 👁️

#94 fix: fixing the loginTests to work correctly.
  webapp/src/tests/Login.test.js
Labels: frontend 👁️

#97 Feat: Questions and answers are now written in the DB!
  questiongenerator/.gitignore
  questiongenerator/mvnw
  questiongenerator/mvnw.cmd
  questiongenerator/pom.xml
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/Answer.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/model/Question.java
  questiongenerator/src/main/java/model/QuestionCategory.java
  questiongenerator/src/main/java/model/QuestionType.java
  questiongenerator/src/main/java/repositories/GeneralRepositoryStorer.java
  questiongenerator/src/main/java/repositories/Jpa.java
  questiongenerator/src/main/java/repositories/Storable.java
  questiongenerator/src/main/java/templates/CountryCapitalQuestion.java
  questiongenerator/src/main/java/templates/QuestionTemplate.java
  questiongenerator/src/main/resources/META-INF/persistence.xml
Labels: backend ⚙️

#99 chore: improving the main readme and adding the wireframes.
  README.md
  docs/images/wireframe-Dashboard.png
  docs/images/wireframe-Game.png
  docs/images/wireframe-Results.png
  docs/images/wireframe-Rules.png
  docs/images/wireframe-SignIn.png
  docs/images/wireframe-SignUp.png
  docs/images/wireframe-Welcome.png
  docs/src/02_architecture_constraints.adoc
Labels: documentation 📜, frontend 👁️

#102 Feat/webapp/new game
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/auth/AuthUtils.js
  webapp/src/components/game/Logout.js
  webapp/src/components/game/Questions.js
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/tests/AuthUtils.test.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Game.test.js
  webapp/src/tests/Login.test.js
  webapp/src/tests/Logout.test.js
  webapp/src/tests/Questions.test.js
  webapp/src/tests/Signup.test.js
Labels: frontend 👁️

#108 Feat/add tests
  webapp/src/tests/AuthUtils.test.js
  webapp/src/tests/Results.test.js
Labels: frontend 👁️, testing 🧪

#113 feat: Adding the icon image to the documentation
  docs/images/icon-image.png
  docs/index.adoc
Labels: documentation 📜

#116 feat: Deleting the help from the documentation
  docs/index.adoc
  docs/src/05_building_block_view.adoc
Labels: documentation 📜

#128 docs: updated sequence, deployment and context diagrams
  docs/diagrams/ActivityDiagramQuestionGenerator
  docs/diagrams/ActivityDiagramSignUp
  docs/diagrams/BusinessContextDiagram.puml
  docs/diagrams/deployment/DeploymentDiagram.puml
  docs/diagrams/sequence/SequenceDiagramGame.puml
  docs/diagrams/sequence/SequenceDiagramLogIn.puml
  docs/diagrams/sequence/SequenceDiagramQuestionGeneration.puml
  docs/diagrams/sequence/SequenceDiagramSignUp.puml
  docs/images/BusinessContext.png
  docs/images/DeploymentDiagram.png
  docs/src/03_system_scope_and_context.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation 📜, ASAP 🚨

#138 Incorporating specific error messages which enhance user experience
  questiongenerator/pom.xml
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/ErrorMessageAlert.jsx
  webapp/src/components/auth/AuthUtils.js
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/tests/AuthUtils.test.js
  webapp/src/tests/Login.test.js
Labels: bug 🐛, frontend 👁️, Visual Enhancements 🎨

#137 feat: auto login when registering user
  api/src/main/java/lab/en2b/quizapi/auth/AuthController.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserRepository.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
  api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java
Labels: backend ⚙️

#142 chore: added prometheus and grafana configuration
  api/monitoring/grafana/provisioning/dashboards/dashboard.yml
  api/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  api/monitoring/grafana/provisioning/datasources/datasources.yml
  api/monitoring/prometheus/prometheus.yml
  api/pom.xml
  api/src/main/resources/application.properties
  docker-compose.yml
Labels: backend ⚙️

#135 Feat/webapp/private routes
  api/src/main/java/lab/en2b/quizapi/auth/AuthController.java
  api/src/test/java/lab/en2b/quizapi/auth/AuthControllerTest.java
  webapp/package-lock.json
  webapp/package.json
  webapp/public/icon-image.png
  webapp/public/index.html
  webapp/src/components/Router.jsx
  webapp/src/components/utils/AuthManager.js
  webapp/src/components/utils/ProtectedRoute.jsx
  webapp/src/tests/AuthManager.test.js
Labels: frontend 👁️

#145 Fix to authManager and statistics frontend support
  webapp/jsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/GoBack.jsx
  webapp/src/components/Router.jsx
  webapp/src/components/auth/AuthManager.js
  webapp/src/components/auth/AuthUtils.js
  webapp/src/components/game/Logout.js
  webapp/src/components/utils/AuthManager.js
  webapp/src/components/utils/ProtectedRoute.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Logout.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/styles/AppView.css
  webapp/src/tests/AuthManager.test.js
  webapp/src/tests/AuthUtils.test.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Login.test.js
  webapp/src/tests/Logout.test.js
  webapp/src/tests/Signup.test.js
  webapp/src/tests/Statistics.test.js
Labels: enhancement 🆕, frontend 👁️, ASAP 🚨

#147 Readme
  README.md
Labels: enhancement 🆕

#148 QoL improvements
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/ButtonEf.jsx
  webapp/src/components/auth/AuthManager.js
  webapp/src/components/game/Questions.js
  webapp/src/components/utils/ProtectedRoute.jsx
  webapp/src/index.js
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Signup.jsx
Labels: enhancement 🆕, frontend 👁️

#149 Fix session not being kept between tabs
  webapp/src/components/auth/AuthManager.js
  webapp/src/pages/Login.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Signup.jsx
Labels: enhancement 🆕

#150 New look and feel
  webapp/package-lock.json
  webapp/package.json
  webapp/public/background.svg
  webapp/public/index.html
  webapp/public/kiwiq-icon.ico
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/ButtonEf.jsx
  webapp/src/components/GoBack.jsx
  webapp/src/components/utils/ProtectedRoute.jsx
  webapp/src/index.js
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Results.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/styles/AppView.css
  webapp/src/styles/theme.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Game.test.js
  webapp/src/tests/Login.test.js
  webapp/src/tests/Results.test.js
  webapp/src/tests/Root.test.js
  webapp/src/tests/Signup.test.js
  webapp/src/tests/Statistics.test.js
Labels: enhancement 🆕, frontend 👁️, ASAP 🚨, Visual Enhancements 🎨

#151 fix: add missing dependency
  webapp/package-lock.json
  webapp/package.json
Labels: frontend 👁️
