Repository Arquisoft/wiq_en2b, pull requests merged in 2024-04, with the labels that each got.

#153 feat: added game workflow
  api/src/main/java/lab/en2b/quizapi/commons/user/User.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserResponseDto.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
  api/src/main/java/lab/en2b/quizapi/commons/user/mappers/UserResponseDtoMapper.java
  api/src/main/java/lab/en2b/quizapi/commons/utils/InsertDataUtils.java
  api/src/main/java/lab/en2b/quizapi/game/Game.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/GameRepository.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameAnswerDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameResponseDto.java
  api/src/main/java/lab/en2b/quizapi/game/mappers/GameResponseDtoMapper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/Question.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/test/java/lab/en2b/quizapi/game/GameControllerTest.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  docker-compose.yml
Labels: backend ⚙️

#152 Refactoring the questions and added new types of questions
  .env
  api/src/main/java/lab/en2b/quizapi/questions/answer/Answer.java
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/Question.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/Answer.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/model/Question.java
  questiongenerator/src/main/java/templates/CountryCapitalQuestion.java
  questiongenerator/src/main/java/templates/QuestionTemplate.java
  questiongenerator/src/main/java/templates/SongQuestion.java
  questiongenerator/src/main/java/templates/StadiumQuestion.java
Labels: enhancement 🆕, backend ⚙️

#156 Fix the webapp tests
  webapp/src/components/utils/ProtectedRoute.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Logout.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/tests/AuthManager.test.js
  webapp/src/tests/Game.test.js
  webapp/src/tests/Questions.test.js
  webapp/src/tests/Signup.test.js
Labels: frontend 👁️, testing 🧪, ASAP 🚨

#159 Added more distractors and fix security hotspot
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
Labels: backend ⚙️

#161 General improvements in the question generator and more
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionCategory.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/model/QuestionCategory.java
  questiongenerator/src/main/java/repositories/GeneralRepositoryStorer.java
  questiongenerator/src/main/java/templates/BallonDOrQuestion.java
Labels: backend ⚙️

#163 New lateral menu
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/LateralMenu.jsx
  webapp/src/components/MenuButton.jsx
  webapp/src/components/Router.jsx
  webapp/src/i18n.js
  webapp/src/pages/About.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/tests/About.test.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Game.test.js
  webapp/src/tests/LateralMenu.test.js
  webapp/src/tests/Signup.test.js
Labels: frontend 👁️, testing 🧪, Visual Enhancements 🎨

#165 Fixing the warnings in the tests.
  webapp/src/components/LateralMenu.jsx
  webapp/src/pages/About.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/LateralMenu.test.js
  webapp/src/tests/Root.test.js
  webapp/src/tests/Rules.test.js
Labels: bug 🐛

#166 Statistics Improvement
  api/src/main/java/lab/en2b/quizapi/auth/dtos/LoginDto.java
  api/src/main/resources/application.properties
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/statistics/UserStatistics.jsx
  webapp/src/pages/About.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/styles/theme.js
  webapp/src/tests/AuthManager.test.js
  webapp/src/tests/Statistics.test.js
  webapp/src/tests/UserStatistics.test.js
Labels: enhancement 🆕, frontend 👁️, testing 🧪, Visual Enhancements 🎨

#168 Remove an unused variable from frontend
  webapp/src/pages/Root.jsx
Labels: frontend 👁️

#167 Docs/game swagger
  api/src/main/java/lab/en2b/quizapi/commons/user/UserResponseDto.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameAnswerDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameResponseDto.java
Labels: documentation 📜, backend ⚙️

#171 fix: async tests
  webapp/src/tests/AuthManager.test.js
  webapp/src/tests/Login.test.js
  webapp/src/tests/Signup.test.js
Labels: enhancement 🆕, frontend 👁️, testing 🧪

#172 Merge from develop to master
  api/src/main/java/lab/en2b/quizapi/auth/dtos/LoginDto.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserResponseDto.java
  api/src/main/java/lab/en2b/quizapi/game/Game.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/GameRepository.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameAnswerDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameResponseDto.java
  api/src/main/java/lab/en2b/quizapi/statistics/Statistics.java
  api/src/main/java/lab/en2b/quizapi/statistics/StatisticsController.java
  api/src/main/java/lab/en2b/quizapi/statistics/StatisticsRepository.java
  api/src/main/java/lab/en2b/quizapi/statistics/StatisticsService.java
  api/src/main/java/lab/en2b/quizapi/statistics/dtos/StatisticsResponseDto.java
  api/src/main/java/lab/en2b/quizapi/statistics/mappers/StatisticsResponseDtoMapper.java
  api/src/main/resources/application.properties
  api/src/test/java/lab/en2b/quizapi/game/GameControllerTest.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  api/src/test/java/lab/en2b/quizapi/statistics/StatisticsControllerTest.java
  api/src/test/java/lab/en2b/quizapi/statistics/StatisticsServiceTest.java
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/LateralMenu.jsx
  webapp/src/components/statistics/UserStatistics.jsx
  webapp/src/pages/About.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/styles/theme.js
  webapp/src/tests/AuthManager.test.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/LateralMenu.test.js
  webapp/src/tests/Login.test.js
  webapp/src/tests/Root.test.js
  webapp/src/tests/Rules.test.js
  webapp/src/tests/Signup.test.js
  webapp/src/tests/Statistics.test.js
  webapp/src/tests/UserStatistics.test.js
Labels: backend ⚙️, frontend 👁️, ASAP 🚨

#174 Various minor QoL fixes to the frontend
  docker-compose.yml
  webapp/src/components/LateralMenu.jsx
Labels: frontend 👁️

#181 Feat/webapp/acceptance
  webapp/e2e/acceptance/user_stories/login_user_stories.txt
  webapp/e2e/acceptance/user_stories/playing_game_user.txt
  webapp/e2e/acceptance/user_stories/register_user_stories.txt
  webapp/e2e/acceptance/user_stories/seeing_stats_stories.txt
  webapp/e2e/features/about_features/positive_logged_user_seeing_about_screen.feature
  webapp/e2e/features/about_features/positive_non_logged_user_seeing_about_screen.feature
  webapp/e2e/features/login_features/negative_bad_format_email_login.feature
  webapp/e2e/features/login_features/negative_blank_email_login.feature
  webapp/e2e/features/login_features/negative_blank_password_login.feature
  webapp/e2e/features/login_features/negative_incorrect_credentials.feature
  webapp/e2e/features/login_features/positive_login.feature
  webapp/e2e/features/logout_features/positive_logged_user_logout.feature
  webapp/e2e/features/logout_features/positive_non_logged_user_logout.feature
  webapp/e2e/features/playing_game_features/negative_non_logged_user_playing_game.feature
  webapp/e2e/features/playing_game_features/positive_playing_game.feature
  webapp/e2e/features/register_form_features/negative_register_blank_email.feature
  webapp/e2e/features/register_form_features/negative_register_blank_password.feature
  webapp/e2e/features/register_form_features/negative_register_blank_repeated_password.feature
  webapp/e2e/features/register_form_features/negative_register_blank_username.feature
  webapp/e2e/features/register_form_features/negative_register_email_already_in_use.feature
  webapp/e2e/features/register_form_features/negative_register_username_already_in_use.feature
  webapp/e2e/features/register_form_features/negative_register_wrong_email_format.feature
  webapp/e2e/features/register_form_features/positive_register_form.feature
  webapp/e2e/features/seeing_rules_features/negative_non_logged_user_seeing_rules.feature
  webapp/e2e/features/seeing_rules_features/positive_seeing_rules.feature
  webapp/e2e/features/seeing_stats_features/negative_non_logged_user_seeing_stats_stories.feature
  webapp/e2e/features/seeing_stats_features/positive_seeing-stats.feature
  webapp/src/tests/Game.test.js
Labels: documentation 📜, testing 🧪

#183 Feat/webapp/game
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/pages/Game.jsx
Labels: frontend 👁️

#190 Documentation improvements
  docs/images/icon-image.png
  docs/images/wireframe-Dashboard.png
  docs/images/wireframe-Game.png
  docs/images/wireframe-Menu.png
  docs/images/wireframe-Results.png
  docs/images/wireframe-Root.png
  docs/images/wireframe-Rules.png
  docs/images/wireframe-SignIn.png
  docs/images/wireframe-SignUp.png
  docs/images/wireframe-Welcome.png
  docs/index.adoc
  docs/src/02_architecture_constraints.adoc
Labels: documentation 📜

#191 Updated the doc and little changes
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/resources/application.properties
  docs/src/08_concepts.adoc
Labels: documentation 📜, backend ⚙️

#195 Docs/docu overview
  docs/src/01_introduction_and_goals.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/09_architecture_decisions.adoc
Labels: documentation 📜

#198 test: initial e2e testing
  .github/workflows/release.yml
  webapp/e2e/features/about_features/positive_logged_user_seeing_about_screen.feature
  webapp/e2e/jest.config.js
  webapp/e2e/steps/about.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/package.json
  webapp/src/components/LateralMenu.jsx
  webapp/src/components/MenuButton.jsx
  webapp/src/pages/About.jsx
Labels: backend ⚙️, frontend 👁️, testing 🧪

#204 Chore: Fixed error in cardinality
  docs/src/08_concepts.adoc
Labels: documentation 📜

#224 HTTPS enablement
  .github/workflows/release.yml
  .gitignore
  api/src/main/resources/application.properties
  docker-compose.yml
  proxy_conf/Dockerfile
  proxy_conf/config.conf
Labels: enhancement 🆕, backend ⚙️, frontend 👁️

#223 New question type
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionCategory.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/model/QuestionCategory.java
  questiongenerator/src/main/java/templates/PaintingQuestion.java
  questiongenerator/src/main/java/templates/VideogamesPublisherQuestion.java
Labels: backend ⚙️

#228 feat: game configuration
  api/src/main/java/lab/en2b/quizapi/commons/utils/GameModeUtils.java
  api/src/main/java/lab/en2b/quizapi/game/Game.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/GameMode.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/CustomGameDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameModeDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameResponseDto.java
  api/src/main/java/lab/en2b/quizapi/game/mappers/GameResponseDtoMapper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/test/java/lab/en2b/quizapi/game/GameControllerTest.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
Labels: backend ⚙️

#230 Feat/user details
  api/src/main/java/lab/en2b/quizapi/commons/user/UserController.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
  api/src/main/java/lab/en2b/quizapi/commons/user/dtos/UserResponseDto.java
  api/src/main/java/lab/en2b/quizapi/commons/user/mappers/UserResponseDtoMapper.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameResponseDto.java
  api/src/main/java/lab/en2b/quizapi/statistics/dtos/StatisticsResponseDto.java
  api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  api/src/test/java/lab/en2b/quizapi/statistics/StatisticsServiceTest.java
  api/src/test/java/lab/en2b/quizapi/user/UserControllerTest.java
  api/src/test/java/lab/en2b/quizapi/user/UserServiceTest.java
Labels: enhancement 🆕, backend ⚙️

#231 Statistics and Rules UI redesign
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/statistics/UserStatistics.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/tests/LateralMenu.test.js
  webapp/src/tests/Statistics.test.js
Labels: frontend 👁️

#233 Feat: Added image questions
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/main/java/lab/en2b/quizapi/questions/question/dtos/QuestionResponseDto.java
  api/src/main/java/lab/en2b/quizapi/questions/question/mappers/QuestionResponseDtoMapper.java
  api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/Question.java
  questiongenerator/src/main/java/repositories/GeneralRepositoryStorer.java
  questiongenerator/src/main/java/templates/PaintingQuestion.java
  questiongenerator/src/main/java/templates/StadiumQuestion.java
Labels: backend ⚙️

#232 Fix the multiple petitions to /auth/refresh
  webapp/src/components/auth/AuthManager.js
  webapp/src/components/utils/ProtectedRoute.jsx
Labels: bug 🐛, frontend 👁️

#235 fix: add proxy deployment on release
  docker-compose.yml
Labels: bug 🐛, ASAP 🚨

#251 Question categories have proper dto
  api/src/main/java/lab/en2b/quizapi/commons/utils/GameModeUtils.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/questions/question/dtos/QuestionCategoryDto.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
Labels: backend ⚙️

#249 Fix: missing 'SELECT' in API
  api/src/main/java/lab/en2b/quizapi/game/GameRepository.java
Labels: bug 🐛, backend ⚙️, ASAP 🚨

#250 Fix: Infinite petitions if user statistics do not exist
  webapp/src/components/statistics/UserStatistics.jsx
Labels: bug 🐛, frontend 👁️, ASAP 🚨

#248 Feat: changing the dashboard
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/Router.jsx
  webapp/src/components/dashboard/CustomGameButton.jsx
  webapp/src/components/dashboard/CustomGameMenu.jsx
  webapp/src/components/dashboard/DashboardButton.jsx
  webapp/src/components/game/Game.js
  webapp/src/components/menu/LateralMenu.jsx
  webapp/src/components/menu/MenuButton.jsx
  webapp/src/components/statistics/UserStatistics.jsx
  webapp/src/components/user/UserInfo.js
  webapp/src/pages/About.jsx
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Results.jsx
  webapp/src/pages/Root.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/styles/theme.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/LateralMenu.test.js
  webapp/src/tests/Results.test.js
Labels: frontend 👁️, Visual Enhancements 🎨

#254 Fix the working game and add image support (without testing)
  api/src/main/java/lab/en2b/quizapi/game/Game.java
  api/src/main/java/lab/en2b/quizapi/game/GameMode.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/CustomGameDto.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameModeDto.java
  api/src/main/java/lab/en2b/quizapi/game/mappers/GameResponseDtoMapper.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionRepository.java
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/dashboard/CustomGameMenu.jsx
  webapp/src/components/game/Game.js
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Login.jsx
  webapp/src/pages/Results.jsx
  webapp/src/pages/Rules.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/styles/theme.js
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/LateralMenu.test.js
Labels: enhancement 🆕, frontend 👁️, Visual Enhancements 🎨

#256 fix: fixed an error checking if the game is active.
  webapp/src/pages/Dashboard.jsx
Labels: bug 🐛, frontend 👁️

#267 More questions
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/repositories/GeneralRepositoryStorer.java
  questiongenerator/src/main/java/templates/BallonDOrQuestion.java
  questiongenerator/src/main/java/templates/BasketballVenueQuestion.java
  questiongenerator/src/main/java/templates/CountryCapitalQuestion.java
  questiongenerator/src/main/java/templates/PaintingQuestion.java
  questiongenerator/src/main/java/templates/QGHelper.java
  questiongenerator/src/main/java/templates/SongQuestion.java
  questiongenerator/src/main/java/templates/StadiumQuestion.java
  questiongenerator/src/main/java/templates/VideogamesCountryQuestion.java
  questiongenerator/src/main/java/templates/VideogamesGenreQuestion.java
  questiongenerator/src/main/java/templates/VideogamesPublisherQuestion.java
  questiongenerator/src/main/java/templates/WhosThatPokemonQuestion.java
Labels: backend ⚙️

#257 fix: re-refreshing not handling correctly page updates
  webapp/src/pages/Game.jsx
Labels: bug 🐛, frontend 👁️, ASAP 🚨

#270 Tests: add game UI tests
  webapp/package-lock.json
  webapp/package.json
  webapp/src/pages/Game.jsx
  webapp/src/tests/Game.test.js
Labels: frontend 👁️, testing 🧪

#272 Tests for dashboard page
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Results.jsx
  webapp/src/tests/Dashboard.test.js
Labels: frontend 👁️, testing 🧪

#271 Updated the readme and the quickstart files
  Quickstart.md
  README.md
Labels: documentation 📜, enhancement 🆕

#273 Add the new tests and fixes to the main branch
  Quickstart.md
  README.md
  webapp/package-lock.json
  webapp/package.json
  webapp/src/pages/Dashboard.jsx
  webapp/src/pages/Game.jsx
  webapp/src/pages/Results.jsx
  webapp/src/tests/Dashboard.test.js
  webapp/src/tests/Game.test.js
Labels: enhancement 🆕

#274 More descriptive errors for the login and signup
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/auth/AuthManager.js
  webapp/src/pages/Login.jsx
  webapp/src/pages/Signup.jsx
  webapp/src/tests/Login.test.js
  webapp/src/tests/Signup.test.js
Labels: frontend 👁️, testing 🧪

#278 Chore: Added country flag questions
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/templates/CountryFlagQuestion.java
Labels: backend ⚙️

#279 Tests/webapp/add
  webapp/src/components/dashboard/DashboardButton.jsx
  webapp/src/pages/Game.jsx
  webapp/src/tests/DashboardButton.test.js
  webapp/src/tests/Game.test.js
Labels: frontend 👁️, testing 🧪

#281 Test: Added coverage for 4 lines because I want the 80%
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
Labels: backend ⚙️, testing 🧪

#283 Fix: Eliminated unnecessary code
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
Labels: backend ⚙️

#284 Fix/sonarcloud analysis
  api/src/main/java/lab/en2b/quizapi/game/Game.java
  api/src/main/java/lab/en2b/quizapi/game/GameController.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/game/dtos/GameAnswerDto.java
  api/src/main/java/lab/en2b/quizapi/questions/answer/Answer.java
  api/src/main/java/lab/en2b/quizapi/questions/question/Question.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/test/java/lab/en2b/quizapi/auth/AuthControllerTest.java
  api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
  api/src/test/java/lab/en2b/quizapi/statistics/StatisticsServiceTest.java
  api/src/test/java/lab/en2b/quizapi/user/UserServiceTest.java
Labels: backend ⚙️

#286 fix: changing language now changes game language
  webapp/src/components/game/Game.js
  webapp/src/pages/Game.jsx
Labels: enhancement 🆕, frontend 👁️

#287 fixed bugs with application
  .github/workflows/release.yml
  api/src/main/java/lab/en2b/quizapi/commons/utils/GameModeUtils.java
  api/src/main/java/lab/en2b/quizapi/game/GameService.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionCategory.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
  api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
  api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
Labels: backend ⚙️

#289 Fixed a bug in the custom game in the dashboard
  webapp/src/components/dashboard/CustomGameMenu.jsx
  webapp/src/components/game/Game.js
Labels: bug 🐛, frontend 👁️

#290 Adding menu button to the results page and goBack buttons follow conventions
  webapp/src/components/GoBack.jsx
  webapp/src/pages/Results.jsx
  webapp/src/pages/Statistics.jsx
Labels: frontend 👁️

#291 feat: updating all the app wireframes.
  docs/images/wireframe-About.png
  docs/images/wireframe-Dashboard-GameModes.png
  docs/images/wireframe-Dashboard-ResumeGame.png
  docs/images/wireframe-Dashboard-UserPanel.png
  docs/images/wireframe-Dashboard-customGameMode.png
  docs/images/wireframe-Dashboard.png
  docs/images/wireframe-Results.png
  docs/images/wireframe-Statistics.png
  docs/src/02_architecture_constraints.adoc
Labels: documentation 📜

#294 Feat: new question type
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/templates/MusicAuthorQuestion.java
Labels: backend ⚙️

#299 Added the QG package distribution
  docs/src/04_solution_strategy.adoc
Labels: documentation 📜

#297 Updated the README
  README.md
Labels: documentation 📜

#300 Fix: VideogamesGenreQuestion
  questiongenerator/src/main/java/templates/VideogamesGenreQuestion.java
Labels: backend ⚙️

#304 fix: page description
  webapp/public/index.html
Labels: enhancement 🆕, frontend 👁️, Visual Enhancements 🎨

#303 Some updates to the docu
  docs/src/12_glossary.adoc
  docs/src/13_annex.adoc
Labels: documentation 📜

#307 Sending error when confirmPassword is blank
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/pages/Signup.jsx
Labels: frontend 👁️

#309 Feat/question publisher date
  api/src/main/java/lab/en2b/quizapi/questions/answer/AnswerCategory.java
  questiongenerator/src/main/java/Main.java
  questiongenerator/src/main/java/model/AnswerCategory.java
  questiongenerator/src/main/java/templates/VideogamesReleaseDate.java
Labels: backend ⚙️

#311 Docs/diego revisited
  docs/src/09_architecture_decisions.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: documentation 📜

#312 Fix: Removed unused variable
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
Labels: backend ⚙️

#313 statistics improvement
  api/src/main/java/lab/en2b/quizapi/auth/dtos/RegisterDto.java
  api/src/main/java/lab/en2b/quizapi/statistics/StatisticsRepository.java
  api/src/main/java/lab/en2b/quizapi/statistics/StatisticsService.java
  api/src/main/java/lab/en2b/quizapi/statistics/dtos/StatisticsResponseDto.java
  api/src/main/java/lab/en2b/quizapi/statistics/mappers/StatisticsResponseDtoMapper.java
  api/src/test/java/lab/en2b/quizapi/statistics/StatisticsServiceTest.java
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/statistics/UserStatistics.jsx
  webapp/src/pages/Statistics.jsx
  webapp/src/tests/Statistics.test.js
Labels: enhancement 🆕, backend ⚙️, frontend 👁️, testing 🧪, Visual Enhancements 🎨

#318 Fixes to the documentation
  docs/index.adoc
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/12_test.adoc
  docs/src/13_glossary.adoc
  docs/src/14_annex.adoc
Labels: documentation 📜

#319 Feat/404 page
  webapp/public/img/kiwi-2.gif
  webapp/public/img/kiwi-3.gif
  webapp/public/img/kiwi.gif
  webapp/public/img/kiwi.png
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/Router.jsx
  webapp/src/components/menu/LateralMenu.jsx
  webapp/src/pages/NotFound.jsx
  webapp/src/tests/PageNotFound404.js
Labels: frontend 👁️
