Repository Arquisoft/wiq_en2b, pull requests merged in 2024-02, with the labels that each got.

#14 feat/initial webapp routing
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/wiq_en2b.iml
  api/.gitignore
  api/.mvn/wrapper/maven-wrapper.jar
  api/.mvn/wrapper/maven-wrapper.properties
  api/mvnw
  api/mvnw.cmd
  api/pom.xml
  api/src/main/java/lab/en2b/quizapi/QuizApiApplication.java
  api/src/main/resources/application.properties
  api/src/test/java/lab/en2b/quizapi/QuizApiApplicationTests.java
  sonar-project.properties
  webapp/jsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Router.jsx
  webapp/src/index.js
  webapp/src/pages/Login.jsx
  webapp/src/pages/Register.jsx
  webapp/src/pages/Root.jsx
  webapp/src/tests/Login.test.js
  webapp/src/tests/Register.test.js
Labels: frontend 👁️

#34 chore: Added sections 9 and 11 to the documentation and terms in the glossary
  docs/src/09_architecture_decisions.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: documentation 📜

#33 Added sections 3 and part of 7 to the documentation
  docs/diagrams/BusinessContextDiagram.puml
  docs/diagrams/ContainerDiagram.puml
  docs/diagrams/DeploymentDiagram.puml
  docs/diagrams/TechnicalContextDiagram.puml
  docs/images/BusinessContext.png
  docs/images/DeploymentDiagram.png
  docs/images/TechnicalContextDiagram.png
  docs/src/03_system_scope_and_context.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation 📜

#32 feat/webapp/top bar: An initial top bar for the layout
  .gitignore
  webapp/jsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/Layout.jsx
  webapp/src/components/Layout.test.js
  webapp/src/components/Router.jsx
  webapp/src/components/pages.json
  webapp/src/i18n.js
  webapp/src/index.js
  webapp/src/pages/Login.jsx
  webapp/src/pages/Register.jsx
  webapp/src/tests/Login.test.js
  webapp/src/tests/Register.test.js
Labels: frontend 👁️

#36 Chore/gonzalo a/docu
  .gitignore
  docs/diagrams/10_Quality_Tree.puml
  docs/images/10_Quality_Tree.png
  docs/index.adoc
  docs/src/01_introduction_and_goals.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/13_annex.adoc
Labels: documentation 📜

#38 Chore/diego/readme update
  Quickstart.md
  README.md
Labels: Visual Enhancements 🎨

#35 docs/jjgancfer
  .gitignore
  docs/src/04_solution_strategy.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation 📜

#40 hotfix: solve docs build error
  docs/src/08_concepts.adoc
Labels: documentation 📜

#43 chore: Updated the UML diagram
  docs/src/08_concepts.adoc
Labels: documentation 📜

#44 Chore: Deleted a file to solve the PR issue
  docs/images/BusinessContext.png
Labels: ASAP 🚨

#37 Chore/sergio q/docu
  docs/images/BusinessContext.png
  docs/images/ContainerDiagram.png
  docs/package.json
  docs/src/05_building_block_view.adoc
Labels: documentation 📜

#46 Changes to make the diagram work in the documentation
  docs/src/02_architecture_constraints.adoc
  docs/src/08_concepts.adoc
Labels: documentation 📜, ASAP 🚨

#48 Merge initial modifications into develop
  .gitignore
  README.md
  api/.gitignore
  api/mvnw
  api/mvnw.cmd
  api/pom.xml
  api/src/main/java/lab/en2b/quizapi/QuizApiApplication.java
  api/src/main/java/lab/en2b/quizapi/auth/AuthController.java
  api/src/main/java/lab/en2b/quizapi/auth/AuthService.java
  api/src/main/java/lab/en2b/quizapi/auth/config/SecurityConfig.java
  api/src/main/java/lab/en2b/quizapi/auth/config/UserDetailsImpl.java
  api/src/main/java/lab/en2b/quizapi/auth/dtos/JwtResponseDto.java
  api/src/main/java/lab/en2b/quizapi/auth/dtos/LoginDto.java
  api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenDto.java
  api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenResponseDto.java
  api/src/main/java/lab/en2b/quizapi/auth/dtos/RegisterDto.java
  api/src/main/java/lab/en2b/quizapi/auth/jwt/JwtAuthFilter.java
  api/src/main/java/lab/en2b/quizapi/auth/jwt/JwtUtils.java
  api/src/main/java/lab/en2b/quizapi/commons/exceptions/CustomControllerAdvice.java
  api/src/main/java/lab/en2b/quizapi/commons/exceptions/TokenRefreshException.java
  api/src/main/java/lab/en2b/quizapi/commons/user/User.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserRepository.java
  api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
  api/src/main/java/lab/en2b/quizapi/commons/user/role/Role.java
  api/src/main/java/lab/en2b/quizapi/commons/user/role/RoleRepository.java
  api/src/main/java/lab/en2b/quizapi/questions/question/QuestionController.java
  api/src/main/resources/application.properties
  api/src/test/java/lab/en2b/quizapi/QuizApiApplicationTests.java
  sonar-project.properties
  webapp/jsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/Layout.jsx
  webapp/src/components/Layout.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/Router.jsx
  webapp/src/components/pages.json
  webapp/src/i18n.js
  webapp/src/index.js
  webapp/src/pages/Root.jsx
Labels: backend ⚙️, frontend 👁️, ASAP 🚨

#55 Code cleanup and http2 in API
  .github/workflows/build.yml
  .github/workflows/release.yml
  api/src/main/resources/application.properties
  gatewayservice/.dockerignore
  gatewayservice/Dockerfile
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/dashboard.yml
  gatewayservice/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  gatewayservice/monitoring/grafana/provisioning/datasources/datasource.yml
  gatewayservice/monitoring/prometheus/prometheus.yml
  gatewayservice/package-lock.json
  gatewayservice/package.json
  sonar-project.properties
  users/authservice/.dockerignore
  users/authservice/Dockerfile
  users/authservice/auth-model.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/authservice/package-lock.json
  users/authservice/package.json
  users/userservice/.dockerignore
  users/userservice/Dockerfile
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
Labels: enhancement 🆕, backend ⚙️
